image: gradle:jre-alpine

# GRADLE_OPTS: Disable the Gradle daemon for Continuous Integration servers as
#   correctness is usually a priority over speed in CI environments.
# GRADLE_USER_HOME: redirect the gradle user home to cache the wrapper and
#   dependencies.
variables:
    GRADLE_OPTS: "-Dorg.gradle.daemon=false"
    GRADLE_USER_HOME: "./.gradle"

# Default cache
cache:
  paths:
    - .gradle

# The assemble task actually builds the project.
# If it fails here, the tests can't run.
build:
  stage: build
  script:
    - ./gradlew clean assemble
  allow_failure: false

# Use the generated build output to run the tests.
test:
  stage: test
  script:
    - ./gradlew check
